### ISSUE TITLE
chore (EditWarning): add docker-compose-ci

### ISSUE THREAD

**Issue by gesinn-it-gea** [gesinn-it/EditWarning#3]

**Comment by gesinn-it-gea** [comment]
It's likely that there are issues with MW 1.39. With DSC39, the following exception is thrown when editing with form:

```
Original exception: [c7aeb7c0c0286f719c90cd8a] [no req] Error: Call to undefined method Wikimedia\Rdbms\DatabaseMysqli::fetchRow()
Backtrace:
from /var/www/html/includes/libs/rdbms/database/DBConnRef.php(103)
#0 /var/www/html/extensions/EditWarning/src/EditWarning.php(108): Wikimedia\Rdbms\DBConnRef->__call()
#1 /var/www/html/extensions/EditWarning/EditWarningHooks.php(249): EditWarning\EditWarning->load()
#2 /var/www/html/includes/HookContainer/HookContainer.php(338): EditWarning\EditWarningHooks::edit()
#3 /var/www/html/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/html/includes/HookContainer/HookRunner.php(946): MediaWiki\HookContainer\HookContainer->run()
#5 /var/www/html/includes/OutputPage.php(2871): MediaWiki\HookContainer\HookRunner->onBeforePageDisplay()
#6 /var/www/html/includes/MediaWiki.php(922): OutputPage->output()
#7 /var/www/html/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/html/index.php(50): MediaWiki->run()
#9 /var/www/html/index.php(46): wfIndexMain()
#10 {main}
```

**Comment by gesinn-it-ilm** [comment]
The wfLoadExtension for EditAccount was not defined in a good way inside LocalSettings.Extensions.php. 

It was like this: **wfLoadExtension("EditAccount.php")** and it was changed and fixed to this **wfLoadExtension("EditAccount")**

_wfLoadExtension("EditAccount.php")_ -> _wfLoadExtension("EditAccount")_

**Comment by gesinn-it-ilm** [comment]
Docker-compose-ci added, matrix for MW 1.35, 1.39 and 1.40. 
PHPUnit tests written and added. 

Composer.json refactored, phpcs and lint working as expected. 
Reported sniffs fixed and cleared. 

_**Exception from above fixed:**_
Instead of **fetchRow()**  --> **foreach loop** used to check each row in database result.
